version: '3'
services:
  webhooks-nodejs:  
    build: node/
    container_name: webhooks-nodejs
    tty: true
    volumes:
      - ../:/app
    working_dir: /app
    environment:
      - queueUrl=
      - NODE_ENV=production
    command: >
      sh -c "yarn --ignore-engines
      && pm2 start -f src/index.js --name="webhooks" --instances 1 --max-memory-restart 150M
      && pm2-docker start daemon-app.js --instances 1"
  webhooks-nginx-sub:
    build: nginx/
    container_name: webhooks-nginx-sub
    links:
      - webhooks-nodejs
    depends_on:
      - webhooks-nodejs
    ports:
      - "8082:8082"
  
